---
- name: "Check mount target {{ mount.target }}"
  become: true
  register: target_state
  ansible.builtin.stat:
    path: "{{ mount.target }}"

- name: "Create mount target {{ mount.target }}"
  become: true
  when:
    - not target_state.stat.exists
    # - not target_state.stat.isdir
  ansible.builtin.file:
    path: "{{ mount.target }}"
    state: directory
    mode: "{{ mount.mode | default('0750') }}"
    owner: "{{ mount.owner | default('root') }}"
    group: "{{ mount.group | default('root') }}"
