---
###### NOTES FOR OPERATE MODE
#### toggle between ansible module "ansible.posix.mount" and "ansible.builtin.template"
#### mount    : can return error and not populate fstab file for some reasons (busy dev...)
####            an option is added to purge fstab content if necessary
#### template : generate file and try a shell "mount -a"

# mount_operate_mode: template
mount_operate_mode: mount
mount_operate_mode_mount_purge: true
mount_operate_mode_template_mount_a: true


####### NOTES FOR SWAP
##### state    : must be "present" if operate in "mount" mode
##### target   : must be "none"
##### fstype   : must be "swap"
##### options  : must be ['sw']


mount_list: []
mount_list_host: []
mount_list_group: []

# mount_list:
#   - target: /boot
#     owner: root
#     group: root
#     mode: "0750"
#     source: /dev/sda1
#     boot: true
#     fstype: ext2
#     options:
#       - defaults
#       - noatime
#     dump: 0
#     pass: 0
#     state: mounted

#   - target: /
#     owner: root
#     group: root
#     mode: "0750"
#     source: /dev/mapper/vg0-lv--root
#     boot: true
#     fstype: xfs
#     options:
#       - defaults
#       - noatime
#     dump: 0
#     pass: 0
#     state: mounted

#   - target: /home
#     owner: root
#     group: root
#     mode: "0750"
#     source: /dev/mapper/vg0-lv--home
#     boot: true
#     fstype: xfs
#     options:
#       - defaults
#       - noatime
#     dump: 0
#     pass: 0
#     state: mounted

#   - target: none
#     owner: root
#     group: root
#     mode: "0750"
#     source: /dev/mapper/vg0-lv--swap
#     boot: true
#     fstype: swap
#     options:
#       - sw
#     dump: 0
#     pass: 1
#     state: present
