---

- name: Purge fstab content
  when:
    - mount_purge_fstab | bool
  ansible.builtin.copy:
    dest: "/etc/fstab"
    content: |
      # Ansible managed
    owner: root
    group: root
    mode: "0644"

- name: Create mount target
  when:
    - not mount.target in "none,/"
    - mount.fstype != "swap"
    - mount.state in "present,mounted,remounted,ephemeral"
  loop: "{{ mount_list + mount_list_host + mount_list_group | flatten(levels=1) }}"
  loop_control:
    loop_var: mount
    label: "source:{{ mount.source }}, target:{{ mount.target }}"
  ansible.builtin.include_tasks:
    file: "sub-tasks/target.yml"

- name: Configure mount
  loop: "{{ mount_list + mount_list_host + mount_list_group | flatten(levels=1) }}"
  loop_control:
    loop_var: mount
    label: "source:{{ mount.source }}, target:{{ mount.target }}"
  ansible.posix.mount:
    boot: "{{ mount.boot | default(omit) }}"
    dump: "{{ mount.dump | default(omit) }}"
    fstype: "{{ mount.fstype | default(omit) }}"
    opts: "{{ mount.options | join(',') | default(omit) }}"
    passno: "{{ mount.pass | default(omit) }}"
    path: "{{ mount.target }}"
    src: "{{ mount.source | default(omit) }}"
    state: "{{ mount.state | default('mounted') }}"

- name: Systemd reload-daemon
  when:
    - ansible_service_mgr == "systemd"
  ansible.builtin.systemd:
    daemon_reload: true
